<?php
declare(strict_types=1);
namespace Hms\Backend;
use RuntimeException; use Throwable;

/** Safe, server-owned HR analytics queries. Metric and dimension keys never become SQL expressions. */
final class DashboardApi {
  private function __construct(private readonly SupabaseClient $supabase) {}
  public static function fromEnvironment(): self { $url=rtrim((string)getenv('SUPABASE_URL'),'/');$key=(string)getenv('SUPABASE_SECRET_KEY');if(!filter_var($url,FILTER_VALIDATE_URL)||$key===''||!function_exists('curl_init'))throw new RuntimeException('Server configuration is incomplete.');return new self(new SupabaseClient($url,$key)); }
  public function dispatch(string $method,string $uri): never { if($method!=='GET')throw new HttpException('Route not found.',404);parse_str((string)parse_url($uri,PHP_URL_QUERY),$q);$actor=$this->actor();$route=array_slice(explode('/',trim((string)parse_url($uri,PHP_URL_PATH),'/')),2);$result=match($route[0]??''){ 'summary'=>$this->summary($q,$actor),'analysis'=>$this->analysis($q,$actor),'employees'=>$this->employees($q,$actor),'trend'=>$this->trend($q,$actor),'attention'=>$this->attention($q,$actor),'overview'=>$this->overview($q,$actor),'secondary'=>$this->secondary($q,$actor),'filter-options'=>$this->filterOptions($actor),'dimensions','options'=>$this->dimensions($actor),default=>throw new HttpException('Route not found.',404)};header('Content-Type: application/json; charset=utf-8');echo json_encode(['data'=>$result],JSON_THROW_ON_ERROR);exit; }
  private function actor():array{$h=$_SERVER['HTTP_AUTHORIZATION']??'';if(!preg_match('/^Bearer\s+(.+)$/i',$h,$m))throw new HttpException('Authentication is required.',401);try{$a=$this->supabase->authUser($m[1]);}catch(Throwable){throw new HttpException('Authentication token is invalid.',401);}$u=$this->supabase->service('GET','/rest/v1/users?select=id,is_active,is_super_admin&auth_user_id=eq.'.rawurlencode((string)($a['id']??'')))[0]??null;if(!is_array($u)||!($u['is_active']??false))throw new HttpException('User account is inactive or not provisioned.',403);$this->allow($u,'dashboard.view');return $u;}
  private function can(array $a,string $p):bool{return $this->canMany($a,[$p])[$p];}
  private function canMany(array $a,array $permissions):array{if(($a['is_super_admin']??false)===true)return array_fill_keys($permissions,true);$requests=[];foreach($permissions as $permission)$requests[]=['method'=>'POST','path'=>'/rest/v1/rpc/user_has_permission','payload'=>['p_user_id'=>$a['id'],'p_permission_key'=>$permission]];$responses=$this->supabase->serviceBatch($requests);$result=[];foreach($permissions as $index=>$permission)$result[$permission]=($responses[$index]??false)===true;return $result;}
  private function allow(array $a,string $p):void{if(!$this->can($a,$p))throw new HttpException('You are not authorized for this action.',403);}
  private function summary(array$q,array$a):array{return $this->summaryRpc($q,$a);}
  private function filters(array $q):array { $allowed=['from','to','department_id','team_id','position_id','project_id','governorate_id','gender','employee_status','employee_classification','leaving_reason_id','shift_type_id','bank_id','marital_status_id','religion_id','diploma_id','search']; $f=[];foreach($allowed as $k)if(isset($q[$k])&&$q[$k]!=='')$f[$k]=(string)$q[$k];return $f; }
  private function analysisRequest(string $metric,string $dimension,array $q):array{return ['method'=>'POST','path'=>'/rest/v1/rpc/dashboard_analysis','payload'=>['p_metric'=>$metric,'p_dimension'=>$dimension,'p_filters'=>$this->filters($q)]];}
  private function analysisResult(string $metric,string $dimension,mixed $raw):array { $data=[];$filterKey=$this->filterKey($dimension);foreach(is_array($raw)?$raw:[] as $row){$data[]=['key'=>$row['key']??null,'label'=>$row['label']??'Unassigned','count'=>(int)($row['count']??0),'filter_key'=>$filterKey];}return ['metric'=>$metric,'dimension'=>$dimension,'total'=>array_sum(array_column($data,'count')),'data'=>$data]; }
  private function rpcAnalysis(string $metric,string $dimension,array $q):array {return $this->analysisResult($metric,$dimension,$this->supabase->serviceBatch([$this->analysisRequest($metric,$dimension,$q)])[0]??[]);}
  private function filterKey(string $dimension):string{if($dimension==='classification')return 'employee_classification';if($dimension==='employee_status'||$dimension==='gender')return $dimension;return $dimension.'_id';}
  private function summaryMetrics():array{return ['total_employees','active_employees','new_hires','resigned_employees','contracts_expiring','missing_form_1'];}
  private function summaryFromRaw(array $metrics,array $responses,array $q):array{$cards=[];foreach($metrics as $index=>$metric){$r=$this->analysisResult($metric,'employee_status',$responses[$index]??[]);$cards[]=['metric'=>$metric,'label'=>ucwords(str_replace('_',' ',$metric)),'count'=>$r['total']];}return ['cards'=>$cards,'period'=>['from'=>$q['from']??null,'to'=>$q['to']??null]];}
  private function summaryRpc(array $q,array $a):array {$metrics=$this->summaryMetrics();$requests=[];foreach($metrics as $metric)$requests[]=$this->analysisRequest($metric,'employee_status',$q);return $this->summaryFromRaw($metrics,$this->supabase->serviceBatch($requests),$q);}
  private function analysis(array$q,array$a):array{$m=(string)($q['metric']??'active_employees');$d=(string)($q['dimension']??'department');$available=$this->dimensions($a);$this->validateMetric($m,$a,$available);$this->validateDimension($d,$a,$available);return $this->rpcAnalysis($m,$d,$q);}
  private function employees(array$q,array$a):array{$m=(string)($q['metric']??'active_employees');$this->validateMetric($m,$a);$page=max(1,(int)($q['page']??1));$size=min(100,max(1,(int)($q['page_size']??25)));$result=$this->supabase->service('POST','/rest/v1/rpc/dashboard_employees',['p_metric'=>$m,'p_filters'=>$this->filters($q),'p_page'=>$page,'p_page_size'=>$size]);return is_array($result)?$result:['rows'=>[],'total'=>0,'page'=>$page,'page_size'=>$size,'total_pages'=>0];}
  private function trend(array$q,array$a):array{$m=(string)($q['metric']??'new_hires');if(!in_array($m,['new_hires','resigned_employees'],true))throw new HttpException('Unsupported trend metric.',422);$from=$q['from']??date('Y-m-01');$to=$q['to']??date('Y-m-d');$granularity=(string)($q['granularity']??'month');$raw=$this->supabase->service('POST','/rest/v1/rpc/dashboard_trend',['p_metric'=>$m,'p_from'=>$from,'p_to'=>$to,'p_granularity'=>$granularity,'p_filters'=>$this->filters($q)]);return ['metric'=>$m,'granularity'=>$granularity,'data'=>is_array($raw)?$raw:[]];}
  private function attention(array$q,array$a):array{$raw=$this->supabase->service('POST','/rest/v1/rpc/dashboard_attention',['p_filters'=>$this->filters($q)]);return ['items'=>is_array($raw)?$raw:[]];}
  private function overview(array$q,array$a):array{$m=(string)($q['metric']??'active_employees');$d=(string)($q['dimension']??'department');$available=$this->dimensions($a);$this->validateMetric($m,$a,$available);$this->validateDimension($d,$a,$available);$metrics=$this->summaryMetrics();$requests=[];foreach($metrics as $metric)$requests[]=$this->analysisRequest($metric,'employee_status',$q);$requests[]=$this->analysisRequest($m,$d,$q);$requests[]=['method'=>'POST','path'=>'/rest/v1/rpc/dashboard_employees','payload'=>['p_metric'=>$m,'p_filters'=>$this->filters($q),'p_page'=>max(1,(int)($q['page']??1)),'p_page_size'=>min(100,max(1,(int)($q['page_size']??25)))]];$requests[]=['method'=>'POST','path'=>'/rest/v1/rpc/dashboard_attention','payload'=>['p_filters'=>$this->filters($q)]];$responses=$this->supabase->serviceBatch($requests);$primaryIndex=count($metrics);return ['summary'=>$this->summaryFromRaw($metrics,array_slice($responses,0,$primaryIndex),$q),'analysis'=>$this->analysisResult($m,$d,$responses[$primaryIndex]??[]),'employees'=>is_array($responses[$primaryIndex+1]??null)?$responses[$primaryIndex+1]:['rows'=>[],'total'=>0,'page'=>1,'page_size'=>10,'total_pages'=>0],'attention'=>['items'=>is_array($responses[$primaryIndex+2]??null)?$responses[$primaryIndex+2]:[]]];}
  private function trendRequest(string $metric,array $q):array{return ['method'=>'POST','path'=>'/rest/v1/rpc/dashboard_trend','payload'=>['p_metric'=>$metric,'p_from'=>$q['from']??date('Y-m-01'),'p_to'=>$q['to']??date('Y-m-d'),'p_granularity'=>(string)($q['granularity']??'month'),'p_filters'=>$this->filters($q)]];}
  private function trendResult(string $metric,array $q,mixed $raw):array{return ['metric'=>$metric,'granularity'=>(string)($q['granularity']??'month'),'data'=>is_array($raw)?$raw:[]];}
  private function secondary(array$q,array$a):array{$m=(string)($q['metric']??'active_employees');$this->validateMetric($m,$a);$specs=[['status','active_employees','employee_status'],['newHireTrend','new_hires',null],['resignTrend','resigned_employees',null]];if($m==='resigned_employees')$specs=array_merge($specs,[['leavingReason',$m,'leaving_reason'],['position',$m,'position'],['department',$m,'department']]);elseif($m==='new_hires')$specs=array_merge($specs,[['position',$m,'position'],['project',$m,'project'],['department',$m,'department']]);else $specs=array_merge($specs,[['department',$m,'department'],['gender','active_employees','gender']]);$requests=[];foreach($specs as [, $metric,$dimension])$requests[]=$dimension===null?$this->trendRequest($metric,$q):$this->analysisRequest($metric,$dimension,$q);$responses=$this->supabase->serviceBatch($requests);$result=[];foreach($specs as $index=>[$key,$metric,$dimension])$result[$key]=$dimension===null?$this->trendResult($metric,$q,$responses[$index]??[]):$this->analysisResult($metric,$dimension,$responses[$index]??[]);return $result;}
  private function filterOptions(array$a):array{$tables=['departments'=>'departments','teams'=>'teams','positions'=>'positions','projects'=>'projects','governorates'=>'governorates','marital-statuses'=>'marital_statuses','religions'=>'religions','diplomas'=>'diplomas','leaving-reasons'=>'leaving_reasons','shift-types'=>'shift_types'];if($this->can($a,'employees.financial.view'))$tables['banks']='banks';$requests=[];foreach($tables as $table)$requests[]=['method'=>'GET','path'=>'/rest/v1/'.$table.'?select=id,name,is_active&order=name'];$responses=$this->supabase->serviceBatch($requests);return array_combine(array_keys($tables),$responses)?:[];}
  private function dimensions(array$a):array{$metrics=['total_employees','active_employees','resigned_employees','inactive_employees','new_hires','five_percent','missing_form_1','missing_form_6','missing_bank','contracts_expiring','contracts_expired','in_probation','probation_due','identity_expiring','identity_expired','licenses_expiring','licenses_expired','open_notifications','due_soon','overdue'];$dimensions=['department','team','position','project','governorate','employee_status','gender','marital_status','religion','diploma','classification','leaving_reason','shift_type'];$permissions=$this->canMany($a,['employees.insurance.view','employees.financial.view']);if($permissions['employees.insurance.view']){$metrics=array_merge($metrics,['medical_eligible','medical_not_yet_eligible','life_eligible','comprehensive_health_participating']);$dimensions[]='comprehensive_health_participation';}if($permissions['employees.financial.view']){$dimensions[]='bank';}return ['metrics'=>$metrics,'dimensions'=>$dimensions,'filter_options'=>['gender'=>[['value'=>'male','label'=>'Male'],['value'=>'female','label'=>'Female']],'employee_status'=>[['value'=>'active','label'=>'Active'],['value'=>'resigned','label'=>'Resigned'],['value'=>'inactive','label'=>'Inactive']],'employee_classification'=>[['value'=>'standard','label'=>'Standard'],['value'=>'five_percent','label'=>'5%']]]];}
  private function validateMetric(string $m,array $a,?array $available=null):void{if(!in_array($m,($available??$this->dimensions($a))['metrics'],true))throw new HttpException('Unsupported dashboard metric.',422);}
  private function validateDimension(string $d,array $a,?array $available=null):void{if(!in_array($d,($available??$this->dimensions($a))['dimensions'],true))throw new HttpException('Unsupported dashboard dimension.',422);}
}
