-- Authentication and role-based access control foundation.

create table if not exists public.users (
  id uuid primary key,
  auth_user_id uuid unique not null references auth.users (id) on delete cascade,
  full_name text not null,
  email text not null,
  phone text,
  is_active boolean not null default true,
  is_super_admin boolean not null default false,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  created_by uuid references public.users (id)
);

create table if not exists public.roles (
  id bigint generated by default as identity primary key,
  name text unique not null,
  description text,
  is_active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  created_by uuid references public.users (id)
);

create table if not exists public.permissions (
  id bigint generated by default as identity primary key,
  permission_key text unique not null,
  module text not null,
  action text not null,
  description text,
  created_at timestamptz not null default now()
);

create table if not exists public.role_permissions (
  role_id bigint not null references public.roles (id) on delete cascade,
  permission_id bigint not null references public.permissions (id) on delete cascade,
  created_at timestamptz not null default now(),
  primary key (role_id, permission_id)
);

create table if not exists public.user_roles (
  user_id uuid not null references public.users (id) on delete cascade,
  role_id bigint not null references public.roles (id) on delete cascade,
  created_at timestamptz not null default now(),
  created_by uuid references public.users (id),
  primary key (user_id, role_id)
);

create table if not exists public.user_permissions (
  user_id uuid not null references public.users (id) on delete cascade,
  permission_id bigint not null references public.permissions (id) on delete cascade,
  effect text not null check (effect in ('allow', 'deny')),
  created_at timestamptz not null default now(),
  created_by uuid references public.users (id),
  primary key (user_id, permission_id)
);

create index if not exists users_email_idx on public.users (email);
create index if not exists users_created_by_idx on public.users (created_by);
create index if not exists roles_created_by_idx on public.roles (created_by);
create index if not exists permissions_module_action_idx on public.permissions (module, action);
create index if not exists role_permissions_permission_id_idx on public.role_permissions (permission_id);
create index if not exists user_roles_role_id_idx on public.user_roles (role_id);
create index if not exists user_roles_created_by_idx on public.user_roles (created_by);
create index if not exists user_permissions_permission_id_idx on public.user_permissions (permission_id);
create index if not exists user_permissions_created_by_idx on public.user_permissions (created_by);

create or replace function public.set_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists users_set_updated_at on public.users;
create trigger users_set_updated_at
before update on public.users
for each row
execute function public.set_updated_at();

drop trigger if exists roles_set_updated_at on public.roles;
create trigger roles_set_updated_at
before update on public.roles
for each row
execute function public.set_updated_at();

insert into public.permissions (permission_key, module, action, description)
values
  ('setup.view', 'setup', 'view', 'View setup'),
  ('setup.edit', 'setup', 'edit', 'Edit setup'),
  ('users.view', 'users', 'view', 'View users'),
  ('users.create', 'users', 'create', 'Create users'),
  ('users.edit', 'users', 'edit', 'Edit users'),
  ('users.deactivate', 'users', 'deactivate', 'Deactivate users'),
  ('roles.view', 'roles', 'view', 'View roles'),
  ('roles.create', 'roles', 'create', 'Create roles'),
  ('roles.edit', 'roles', 'edit', 'Edit roles'),
  ('roles.delete', 'roles', 'delete', 'Delete roles'),
  ('employees.view', 'employees', 'view', 'View employees'),
  ('employees.create', 'employees', 'create', 'Create employees'),
  ('employees.edit', 'employees', 'edit', 'Edit employees'),
  ('employees.delete', 'employees', 'delete', 'Delete employees'),
  ('employees.personal.view', 'employees.personal', 'view', 'View employee personal information'),
  ('employees.personal.edit', 'employees.personal', 'edit', 'Edit employee personal information'),
  ('employees.work.view', 'employees.work', 'view', 'View employee work information'),
  ('employees.work.edit', 'employees.work', 'edit', 'Edit employee work information'),
  ('employees.insurance.view', 'employees.insurance', 'view', 'View employee insurance information'),
  ('employees.insurance.edit', 'employees.insurance', 'edit', 'Edit employee insurance information'),
  ('employees.financial.view', 'employees.financial', 'view', 'View employee financial information'),
  ('employees.financial.edit', 'employees.financial', 'edit', 'Edit employee financial information'),
  ('dashboard.view', 'dashboard', 'view', 'View dashboard')
on conflict (permission_key) do nothing;
