-- Employees backend foundation. SetUp remains the sole source for lookup data.

create table public.employees (
  id uuid primary key default gen_random_uuid(),
  employee_number bigint not null unique,
  employee_status text not null default 'active' check (employee_status in ('active', 'resigned', 'inactive')),
  employee_classification text not null default 'standard' check (employee_classification in ('standard', 'five_percent')),
  gender text not null check (gender in ('male', 'female')),
  arabic_full_name text not null check (nullif(btrim(arabic_full_name), '') is not null),
  english_full_name text not null check (nullif(btrim(english_full_name), '') is not null),
  identity_card_number text not null unique check (identity_card_number ~ '^[0-9]{14}$'),
  identity_card_expiration_date date not null,
  date_of_birth date not null check (date_of_birth <= current_date),
  religion_id bigint not null references public.religions(id) on delete restrict,
  marital_status_id bigint not null references public.marital_statuses(id) on delete restrict,
  diploma_id bigint references public.diplomas(id) on delete restrict,
  major text,
  graduated_from text,
  phone text not null check (phone ~ '^[0-9]{11}$'),
  governorate_id bigint not null references public.governorates(id) on delete restrict,
  address text,
  department_id bigint not null references public.departments(id) on delete restrict,
  shift_type_id bigint not null references public.shift_types(id) on delete restrict,
  team_id bigint references public.teams(id) on delete restrict,
  position_id bigint not null references public.positions(id) on delete restrict,
  project_id bigint references public.projects(id) on delete restrict,
  joining_date date not null,
  contract_signing_date date not null,
  contract_expiration_date date generated always as ((contract_signing_date + interval '1 year - 1 day')::date) stored,
  probation_due_date date generated always as ((joining_date + interval '3 months - 1 day')::date) stored,
  social_insurance_active boolean not null default false,
  social_insurance_comment text,
  form_1_incoming_number text,
  form_1_incoming_date date,
  bank_id bigint references public.banks(id) on delete restrict,
  leaving_date date,
  leaving_reason_id bigint references public.leaving_reasons(id) on delete restrict,
  leaving_comment text,
  annual_days_settled numeric(8,2) check (annual_days_settled is null or annual_days_settled >= 0),
  form_6_incoming_number text,
  form_6_incoming_date date,
  form_6_reason text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  created_by uuid not null references public.users(id) on delete restrict,
  updated_by uuid references public.users(id) on delete restrict,
  check (contract_signing_date >= joining_date),
  check (employee_status = 'active' or (leaving_date is not null and leaving_reason_id is not null))
);

create table public.employee_wives (
  id bigint generated by default as identity primary key,
  employee_id uuid not null references public.employees(id) on delete restrict,
  wife_name text not null check (nullif(btrim(wife_name), '') is not null),
  identity_card_number text not null check (identity_card_number ~ '^[0-9]{14}$'),
  is_working boolean not null default false,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  created_by uuid not null references public.users(id) on delete restrict,
  updated_by uuid references public.users(id) on delete restrict,
  unique (employee_id, identity_card_number)
);

create table public.employee_children (
  id bigint generated by default as identity primary key,
  employee_id uuid not null references public.employees(id) on delete restrict,
  wife_id bigint references public.employee_wives(id) on delete restrict,
  child_name text not null check (nullif(btrim(child_name), '') is not null),
  identity_card_number text not null check (identity_card_number ~ '^[0-9]{14}$'),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  created_by uuid not null references public.users(id) on delete restrict,
  updated_by uuid references public.users(id) on delete restrict,
  unique (employee_id, identity_card_number)
);

create table public.employee_licenses (
  id bigint generated by default as identity primary key,
  employee_id uuid not null references public.employees(id) on delete restrict,
  license_type_id bigint not null references public.license_types(id) on delete restrict,
  release_date date not null,
  expiry_date date not null check (expiry_date >= release_date),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  created_by uuid not null references public.users(id) on delete restrict,
  updated_by uuid references public.users(id) on delete restrict
);

create table public.employee_contract_renewals (
  id bigint generated by default as identity primary key,
  employee_id uuid not null references public.employees(id) on delete restrict,
  previous_contract_signing_date date not null,
  previous_contract_expiration_date date not null,
  renewal_signing_date date not null,
  renewal_expiration_date date not null,
  created_at timestamptz not null default now(),
  created_by uuid not null references public.users(id) on delete restrict,
  check (renewal_expiration_date = (renewal_signing_date + interval '1 year - 1 day')::date)
);

create table public.employee_notifications (
  id bigint generated by default as identity primary key,
  employee_id uuid not null references public.employees(id) on delete restrict,
  notification_type text not null check (notification_type in ('identity_card_expiry', 'license_expiry', 'form_1_deadline', 'medical_insurance_eligibility', 'life_insurance_eligibility')),
  -- Zero represents an employee-level source; license reminders use the license ID.
  -- Non-null is required so the uniqueness guarantee remains effective in PostgreSQL.
  source_id bigint not null default 0,
  due_date date not null,
  reminder_threshold_days integer not null check (reminder_threshold_days >= 0),
  reference_key text not null,
  deep_link text not null,
  status text not null default 'open' check (status in ('open', 'read', 'dismissed', 'resolved')),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (employee_id, notification_type, source_id, reminder_threshold_days)
);

create index employees_status_idx on public.employees (employee_status);
create index employees_department_idx on public.employees (department_id);
create index employees_team_idx on public.employees (team_id);
create index employees_position_idx on public.employees (position_id);
create index employees_project_idx on public.employees (project_id);
create index employees_governorate_idx on public.employees (governorate_id);
create index employees_name_search_idx on public.employees using gin (to_tsvector('simple', coalesce(arabic_full_name, '') || ' ' || coalesce(english_full_name, '') || ' ' || employee_number::text));
create index employee_wives_employee_idx on public.employee_wives (employee_id);
create index employee_children_employee_idx on public.employee_children (employee_id);
create index employee_licenses_employee_idx on public.employee_licenses (employee_id);
create index employee_licenses_expiry_idx on public.employee_licenses (expiry_date);
create index employee_contract_renewals_employee_idx on public.employee_contract_renewals (employee_id, renewal_signing_date desc);
create index employee_notifications_employee_status_idx on public.employee_notifications (employee_id, status, due_date);
create index employee_notifications_due_idx on public.employee_notifications (due_date, status);

create or replace function public.assign_employee_number()
returns trigger language plpgsql as $$
begin
  if new.employee_number is not null then
    raise exception 'Employee ID is generated by the system';
  end if;
  perform pg_advisory_xact_lock(pg_catalog.hashtext('hms.employee_number'));
  select coalesce(max(employee_number), 0) + 1 into new.employee_number from public.employees;
  return new;
end;
$$;

create or replace function public.prevent_employee_number_change()
returns trigger language plpgsql as $$
begin
  if new.employee_number <> old.employee_number then
    raise exception 'Employee ID is immutable';
  end if;
  return new;
end;
$$;

create or replace function public.ensure_child_wife_belongs_to_employee()
returns trigger language plpgsql as $$
begin
  if new.wife_id is not null and not exists (
    select 1 from public.employee_wives where id = new.wife_id and employee_id = new.employee_id
  ) then
    raise exception 'Child wife must belong to the same employee';
  end if;
  return new;
end;
$$;

create or replace function public.refresh_employee_notifications(p_employee_id uuid, p_as_of date default current_date)
returns void language plpgsql security definer set search_path = pg_catalog, public, pg_temp as $$
declare
  v_employee public.employees%rowtype;
  v_medical_months integer;
  v_life_months integer;
  v_form_1_deadline date;
begin
  select * into v_employee from public.employees where id = p_employee_id;
  if not found then raise exception 'Employee does not exist'; end if;
  select value::integer into v_medical_months from public.insurance_settings where setting_key = 'medical_insurance_eligibility_months' and is_active;
  select value::integer into v_life_months from public.insurance_settings where setting_key = 'life_insurance_eligibility_months' and is_active;
  v_form_1_deadline := (v_employee.contract_signing_date + interval '1 month')::date;

  insert into public.employee_notifications (employee_id, notification_type, source_id, due_date, reminder_threshold_days, reference_key, deep_link)
  select v_employee.id, 'identity_card_expiry', 0, v_employee.identity_card_expiration_date, threshold_days, 'personal.identity_card_expiration_date', '/employees/' || v_employee.id || '#identity-card'
  from unnest(array[30, 14, 7]) as threshold_days
  where case threshold_days
    when 30 then (v_employee.identity_card_expiration_date - interval '1 month')::date
    else v_employee.identity_card_expiration_date - threshold_days
  end <= p_as_of
  on conflict (employee_id, notification_type, source_id, reminder_threshold_days) do update
    set due_date = excluded.due_date, updated_at = now()
    where employee_notifications.status = 'open';

  insert into public.employee_notifications (employee_id, notification_type, source_id, due_date, reminder_threshold_days, reference_key, deep_link)
  select l.employee_id, 'license_expiry', l.id, l.expiry_date, threshold_days, 'licenses.' || l.id, '/employees/' || l.employee_id || '#licenses'
  from public.employee_licenses l cross join unnest(array[30, 14, 7]) as threshold_days
  where l.employee_id = v_employee.id and case threshold_days
    when 30 then (l.expiry_date - interval '1 month')::date
    else l.expiry_date - threshold_days
  end <= p_as_of
  on conflict (employee_id, notification_type, source_id, reminder_threshold_days) do update
    set due_date = excluded.due_date, updated_at = now()
    where employee_notifications.status = 'open';

  insert into public.employee_notifications (employee_id, notification_type, source_id, due_date, reminder_threshold_days, reference_key, deep_link)
  select v_employee.id, 'form_1_deadline', 0, v_form_1_deadline, threshold_days, 'insurance.form_1_incoming_date', '/employees/' || v_employee.id || '#form-1'
  from unnest(array[21, 7]) as threshold_days
  where v_employee.form_1_incoming_date is null and v_form_1_deadline - threshold_days <= p_as_of
  on conflict (employee_id, notification_type, source_id, reminder_threshold_days) do update
    set due_date = excluded.due_date, updated_at = now()
    where employee_notifications.status = 'open';

  insert into public.employee_notifications (employee_id, notification_type, source_id, due_date, reminder_threshold_days, reference_key, deep_link)
  select v_employee.id, 'medical_insurance_eligibility', 0, (v_employee.joining_date + make_interval(months => coalesce(v_medical_months, 0)))::date, 0, 'insurance.medical', '/employees/' || v_employee.id || '#medical-insurance'
  where (v_employee.joining_date + make_interval(months => coalesce(v_medical_months, 0)))::date <= p_as_of
  on conflict (employee_id, notification_type, source_id, reminder_threshold_days) do update set due_date = excluded.due_date, updated_at = now() where employee_notifications.status = 'open';

  insert into public.employee_notifications (employee_id, notification_type, source_id, due_date, reminder_threshold_days, reference_key, deep_link)
  select v_employee.id, 'life_insurance_eligibility', 0, (v_employee.joining_date + make_interval(months => coalesce(v_life_months, 0)))::date, 0, 'insurance.life', '/employees/' || v_employee.id || '#life-insurance'
  where (v_employee.joining_date + make_interval(months => coalesce(v_life_months, 0)))::date <= p_as_of
  on conflict (employee_id, notification_type, source_id, reminder_threshold_days) do update set due_date = excluded.due_date, updated_at = now() where employee_notifications.status = 'open';

  if v_employee.form_1_incoming_date is not null then
    update public.employee_notifications
    set status = 'resolved', updated_at = now()
    where employee_id = v_employee.id and notification_type = 'form_1_deadline' and status = 'open';
  end if;
end;
$$;

create or replace function public.renew_employee_contract(p_employee_id uuid, p_renewal_signing_date date, p_actor_id uuid)
returns public.employee_contract_renewals language plpgsql security definer set search_path = pg_catalog, public, pg_temp as $$
declare
  v_employee public.employees%rowtype;
  v_renewal public.employee_contract_renewals%rowtype;
begin
  select * into v_employee from public.employees where id = p_employee_id for update;
  if not found then raise exception 'Employee does not exist'; end if;
  if p_renewal_signing_date is null or p_renewal_signing_date < v_employee.joining_date then
    raise exception 'Renewal signing date must be on or after joining date';
  end if;
  insert into public.employee_contract_renewals (
    employee_id, previous_contract_signing_date, previous_contract_expiration_date,
    renewal_signing_date, renewal_expiration_date, created_by
  ) values (
    v_employee.id, v_employee.contract_signing_date, v_employee.contract_expiration_date,
    p_renewal_signing_date, (p_renewal_signing_date + interval '1 year - 1 day')::date, p_actor_id
  ) returning * into v_renewal;
  update public.employees set contract_signing_date = p_renewal_signing_date, updated_by = p_actor_id where id = p_employee_id;
  return v_renewal;
end;
$$;

create trigger employees_assign_number before insert on public.employees for each row execute function public.assign_employee_number();
create trigger employees_prevent_number_change before update on public.employees for each row execute function public.prevent_employee_number_change();
create trigger employees_set_updated_at before update on public.employees for each row execute function public.set_updated_at();
create trigger employee_wives_set_updated_at before update on public.employee_wives for each row execute function public.set_updated_at();
create trigger employee_children_set_updated_at before insert or update on public.employee_children for each row execute function public.ensure_child_wife_belongs_to_employee();
create trigger employee_children_set_updated_at_2 before update on public.employee_children for each row execute function public.set_updated_at();
create trigger employee_licenses_set_updated_at before update on public.employee_licenses for each row execute function public.set_updated_at();
create trigger employee_notifications_set_updated_at before update on public.employee_notifications for each row execute function public.set_updated_at();

alter table public.employees enable row level security;
alter table public.employee_wives enable row level security;
alter table public.employee_children enable row level security;
alter table public.employee_licenses enable row level security;
alter table public.employee_contract_renewals enable row level security;
alter table public.employee_notifications enable row level security;
revoke all on public.employees, public.employee_wives, public.employee_children, public.employee_licenses, public.employee_contract_renewals, public.employee_notifications from anon, authenticated;
revoke all on function public.refresh_employee_notifications(uuid, date) from public, anon, authenticated;
revoke all on function public.renew_employee_contract(uuid, date, uuid) from public, anon, authenticated;
grant execute on function public.refresh_employee_notifications(uuid, date) to service_role;
grant execute on function public.renew_employee_contract(uuid, date, uuid) to service_role;
